spring:
  profiles:
    active:
     - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: zhou-test
eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:38130/eureka/
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: zhou-test
eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:38131/eureka/
